import {
  Atom,
  Braces,
  Cloud,
  Code2,
  Cpu,
  Database,
  Film,
  FlaskConical,
  GitBranch,
  HardDrive,
  Layers3,
  MonitorCheck,
  Network,
  PanelsTopLeft,
  Server,
  ShieldCheck,
  Sparkles,
  TrainFront,
  Triangle,
  WandSparkles,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  react: Atom,
  "next.js": Triangle,
  nextjs: Triangle,
  typescript: Braces,
  javascript: Braces,
  html: Code2,
  css: PanelsTopLeft,
  tailwind: Layers3,
  "tailwind css": Layers3,
  node: Server,
  "node.js": Server,
  express: Network,
  "express.js": Network,
  rest: Network,
  postgresql: Database,
  postgres: Database,
  ffmpeg: Film,
  openai: Sparkles,
  tensorflow: Cpu,
  s3: HardDrive,
  aws: Cloud,
  git: GitBranch,
  vite: Zap,
  eslint: ShieldCheck,
  prettier: WandSparkles,
  vitest: FlaskConical,
  playwright: MonitorCheck,
  vercel: Triangle,
  railway: TrainFront,
};

export function StackIcon({ label }: { label: string }) {
  const Icon = iconMap[label.toLowerCase()] ?? Code2;
  return <Icon className="size-3" strokeWidth={1.8} aria-hidden="true" />;
}
